### ISSUE TITLE
If it's possible to network boot multi OS use berryboot?

### ISSUE THREAD

**Issue by yangxuan8282** [agoldcheidt/archlinux-for-berryboot#2]
Since raspberry pi 3 support network boot, and I'm thinking if it's possible to use berryboot boot multi system from network. 
I extract berryboot to tftpboot folder, and setup dnsmasq follow the official [documents](https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/net_tutorial.md), the boot success, I can see the berryboot menu, but when I try to install os to usb stick it failed. I'm wonder if it's possible to use use berryboot boot an exist OS(like archlinux arm or raspbain ) in NFS server?

**Comment by agoldcheidt** [comment]
Hi @yangxuan8282 I'm so sorry for the late reply, I don't have an answer to that question but I'm sure the [Berryboot Developer](https://github.com/maxnet/berryboot) will guide you or at least add it as request in Berryboot future features.
